{
  "hash": "60937f0c10cacd4e1fbfa15764429fe9",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Writing controlledburn output in parallel\"\ndescription: \"The serial COG write loop from the last post, replaced by 24 workers writing disjoint Zarr chunks. The 31-billion-cell grid on disk in 28 seconds of 9.5 MB.\"\nauthor: \"Michael Sumner\"\ndate: \"2026-09-03\"\ncategories: [controlledburn, rasterization, Antarctica, GDAL, Zarr, mirai]\nformat:\n  html:\n    code-fold: false\n    toc: true\nexecute:\n  eval: false\n---\n\nIn [Rasterizing ice-free Antarctica](../2026-08-19_antarctica-icefree-rasterizing/) the\nrasterization itself was fast, and the slow part was the file. The\nwrite loop visited about 8000 super-tiles, materializing each one from the sparse\nburn and pushing it into a COG through a single dataset handle. That handle is the\nwhole problem: the COG driver's create path writes a temporary GeoTIFF and then\nrewrites it on close, and neither step tolerates a second writer.\n\nEvery iteration of that loop is independent - crop, materialize, write - and the\nburn object it reads from is 27 MB. The only thing shared is the sink. So change the\nsink.\n\n## Why Zarr\n\nA Zarr array is a small metadata file plus one file per chunk. Two processes writing\ndifferent chunks never touch the same bytes, so there is nothing to coordinate. GDAL's\nZarr driver also declines to write a chunk that is entirely fill value (it will even\nunlink an existing one), which means the store on disk *is* the sparse representation:\nchunks over open ocean and interior ice sheet do not exist.\n\nThe plan is\n\n1. create the empty store once, in the parent, with GDAL\n2. open it in update mode from each worker, with its own handle, and write whole chunks\n3. if a COG is still wanted, make it with one `translate()` at the end\n\n\n## Instantiate\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(controlledburn)\nlibrary(gdalraster)\nlibrary(mirai)\n\next <- ba$extent\ndm  <- ba$dimension\nchunk_size <- 2048L\nzarr_path  <- file.path(tempdir(), \"rema_approx.zarr\")\n\nds <- create(\n  format = \"Zarr\", dst_filename = zarr_path,\n  xsize = dm[1], ysize = dm[2], nbands = 1, dataType = \"Int32\",\n  options = c(paste0(\"BLOCKSIZE=\", chunk_size, \",\", chunk_size),\n              \"COMPRESS=ZSTD\", \"FORMAT=ZARR_V2\"),\n  return_obj = TRUE)\nds$setGeoTransform(vaster::extent_dim_to_gt(ext, dm))\nds$setProjection(raster_info$projection$Wkt)\nds$setNoDataValue(band = 1, 0)   # fill_value; all-zero chunks are never written\nds$close()\n```\n:::\n\n\nThe 4x4 \"super-tile\" from the last post is gone. A chunk write is one file write, so\nthe chunk is the natural unit of parallel work; 2048 keeps each dense allocation at\n16 MB for Int32. (If 512-pixel chunks are wanted for cloud reads, set `BLOCKSIZE=512,512`\nand keep iterating over 2048 windows; GDAL splits each write into 16 chunk files that\nare still disjoint per worker.)\n\n## Populate\n\nThe tile index and the pre-filter to rows that carry data are unchanged. The worker\nopens the store in update mode, writes a batch of chunks, and closes. It calls nothing\nthat dirties metadata, so `.zarray` and `.zmetadata` are not rewritten on close.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_tiles <- function(tile_batch, zarr_path) {\n  ds <- methods::new(gdalraster::GDALRaster, zarr_path, read_only = FALSE)\n  on.exit(ds$close(), add = TRUE)\n  n <- 0L\n  for (i in seq_len(nrow(tile_batch))) {\n    t <- tile_batch[i, ]\n    sub <- controlledburn::crop_burn(ba, c(t$xmin, t$xmax, t$ymin, t$ymax))\n    if (nrow(sub$runs) == 0 && nrow(sub$edges) == 0) next\n    mat <- controlledburn::materialize_chunk(sub, fun = \"id\")\n    mat[is.na(mat)] <- 0L\n    ds$write(band = 1, xoff = t$offset_x, yoff = t$offset_y,\n             xsize = t$ncol, ysize = t$nrow, rasterData = as.integer(t(mat)))\n    n <- n + 1L\n  }\n  n\n}\nenvironment(write_tiles) <- globalenv()\n\ndaemons(24)\neverywhere(library(controlledburn), ba = ba)   # ships ba once per daemon\n\nbatches <- split(tiles, cut(seq_len(nrow(tiles)), 24 * 4L, labels = FALSE))\nsystem.time({\n  res <- mirai_map(batches, write_tiles, .args = list(zarr_path = zarr_path))[.progress]\n})\ndaemons(0)\n```\n:::\n\n\nTwo `mirai` details that cost me a round trip. Objects passed through `...` to\n`everywhere()` are assigned into each daemon's global environment, which is exactly\nthe \"send the 27 MB once\" behaviour wanted here; a plain `<-` inside the expression is\nevaluated in a clean environment and lost (use `<<-` if you assign there). And\nreparenting the worker function to `globalenv()` stops it dragging the Quarto chunk\nenvironment along with every task.\n\n## Result\n\nOn a 32-cpu, 64 GB machine with 24 daemons:\n\n```\n   user  system elapsed\n  ...     ...    28.0\n```\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(terra)\nrast(zarr_path)\n#> class       : SpatRaster\n#> size        : 182568, 170318, 1  (nrow, ncol, nlyr)\n#> resolution  : 32, 32  (x, y)\n#> extent      : -2700096, 2750080, -2500096, 3342080  (xmin, xmax, ymin, ymax)\n#> source      : rema_approx.zarr\n\nf0 <- fs::dir_ls(zarr_path, recurse = TRUE)\nlength(f0)\n#> [1] 722\nsum(fs::file_size(f0))\n#> 9.48M\n```\n:::\n\n\nThe grid could hold ceiling(170318 / 2048) x ceiling(182568 / 2048) = 84 x 90 = 7560\nchunks. About 718 of them exist. That is 9.5% of the continent's bounding box with any\nrock in it at the 2048-pixel scale, a number obtained by listing a directory, and the\nwhole store is 9.5 MB - alongside the 27 MB burn object, the 5.6 MB DEFLATE COG, and\nthe 613 MB uncompressed AADC product from last time, it is another point on the same\ncontinuum.\n\n## Coda: the COG is now cheap\n\nIf the COG is still the deliverable, the expensive part - materializing every tile -\nhas already happened in parallel. What remains is one sequential translate, I/O-bound,\nwith the COG driver's own threads handling compression and overviews:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset_config_option(\"GDAL_NUM_THREADS\", \"ALL_CPUS\")\ntranslate(zarr_path, file.path(tempdir(), \"rema_approx.tif\"),\n          cl_arg = c(\"-of\", \"COG\", \"-co\", \"BLOCKSIZE=512\", \"-co\", \"SPARSE_OK=YES\",\n                     \"-co\", \"COMPRESS=DEFLATE\", \"-co\", \"OVERVIEW_RESAMPLING=NEAREST\",\n                     \"-co\", \"NUM_THREADS=ALL_CPUS\"))\n```\n:::\n\n\nThings I have not done yet, and want to:\n\n- Time this step, so there is an honest end-to-end \"how long to get a COG\" number\n  against the original serial loop.\n- Check whether reading a sparse Zarr into the COG driver preserves sparsity as well\n  as writing blocks directly did (`SPARSE_OK=YES` should skip the absent chunks, which\n  come back as nodata).\n- The Zarr driver has no classic-API overviews; for a Zarr-native product the\n  pyramid would be additional arrays (the multiscales convention in GDAL 3.13 for\n  Zarr V3), which is a separate post.\n\n## Appendix: populating without GDAL in the workers\n\nThe other question I set out with was whether GDAL could instantiate the store and\nsomething more generic could fill it. It can. A Zarr V2 chunk is: the full chunk shape\n(edge chunks padded with `fill_value`), C order, the declared dtype (`<i4` here),\npassed through the declared compressor, saved as `row.col` in the array directory,\n0-based. If the store is created with `COMPRESS=ZLIB`, base R already has the encoder,\nbecause `memCompress(type = \"gzip\")` emits a zlib stream, which is what the numcodecs\n`zlib` codec expects.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_chunk_raw <- function(mat, row_chunk, col_chunk, array_dir, chunk_size) {\n  full <- matrix(0L, chunk_size, chunk_size)\n  full[seq_len(nrow(mat)), seq_len(ncol(mat))] <- mat\n  bytes <- writeBin(as.integer(t(full)), raw(), size = 4L, endian = \"little\")\n  writeBin(memCompress(bytes, type = \"gzip\"),\n           file.path(array_dir, sprintf(\"%d.%d\", row_chunk, col_chunk)))\n}\n```\n:::\n\n\nThis has no shared writes of any kind, not even the metadata files, and it is the\nmirror image of a Zarr *reader*, which is where I am headed with `zaro`. Open\nquestions to explore:\n\n- ZSTD or Blosc from R without pulling in a heavy dependency, since ZLIB is the slow\n  codec.\n- Whether the worker should write chunks at all, or emit `(chunk key, bytes)` pairs so\n  the sink can be a local directory, an object store, or something that builds a\n  kerchunk/Icechunk reference set instead.\n- Doing the same for the coverage-mode burn (`Float32`, `<f4`), where the chunks are\n  no longer mostly a single value and the compressor choice matters more.\n\n::: {.callout-note}\n## A note on the surrounding tools\n\nAs before, this leans on tools in active development - `controlledburn`, `grout`,\n`vaster` - and on `gdalraster` and `mirai`, which are not. The Zarr driver's behaviour\nunder concurrent update (metadata rewritten only when dirtied, empty chunks skipped)\nis what I observed here and what a reading of the driver suggests, but it is not a\ndocumented guarantee; check the `.zmetadata` mtime and the chunk-file count on a small\ngrid before trusting it on a large one.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}