{
  "hash": "e0bb05e2e63fdb52f3c54e0ad6fbdd3b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Distance, perimeter and area in sf and terra: which number do you get?\"\nauthor: \"Michael Sumner\"\ndate: \"2026-09-24\"\nformat:\n  html:\n    code-fold: false\n    toc: true\nexecute:\n  echo: true\n  warning: true\n  message: false\n---\n\n\n\nIn May 2025 a question on R-sig-Geo asked why `sf::st_perimeter()` gave a\ndifferent answer from `sf::st_length(sf::st_boundary())` for the same small\nland parcel in France, with spherical geometry switched off\n([thread](https://stat.ethz.ch/pipermail/r-sig-geo/2025-May/029541.html)).\nThere were three different numbers for the perimeter of that parcel, and each\nof them is correct for a particular model of the Earth and a particular\nmeaning of \"edge\". I posted a\n[gist](https://gist.github.com/mdsumner/5daedfcbee851ca31a7aa9006dbf74cf)\nat the time as a start at unpicking them. (In my message on that thread,\n\"sf+longlat-s2 uses Karney\" should read \"with s2 switched off\".)\n\nThe specific inconsistency in `st_perimeter()` has since been fixed in sf\n([#2541](https://github.com/r-spatial/sf/issues/2541)). What remains is the\nmore general question this post is about: for a given geometry, how does each\npackage decide which model of the Earth to measure on, and can a user predict\nthe answer from the data in front of them?\n\nThe short version:\n\n* **terra** decides from the geometry's coordinate reference system. Longitude\n  and latitude input is always measured on the ellipsoid. Projected input is\n  measured on the ellipsoid for area and cell size (by default), and in the\n  plane for perimeter and distance.\n* **sf** decides from the coordinate reference system *and* a session option,\n  `sf_use_s2()`. Longitude and latitude input is measured on a sphere when s2\n  is on (the default) and on the ellipsoid when it is off. Projected input is\n  always measured in the plane. The same option also selects the engine used\n  for predicates and overlay operations.\n\nThe rest of the post establishes this with code, and then looks at how large\nthe differences are and where they come from.\n\n## Versions\n\nEverything below depends on these versions, and the results should be re-run\nwhen they change.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npkgs <- c(\"sf\", \"terra\", \"s2\", \"lwgeom\", \"geosphere\", \"geodist\", \"wk\")\nvapply(pkgs, function(p) as.character(utils::packageVersion(p)), \"\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       sf     terra        s2    lwgeom geosphere   geodist        wk \n  \"1.1.3\"  \"1.9.50\"  \"1.1.12\"  \"0.2.17\"   \"1.6.8\"   \"0.1.1\"   \"0.9.5\" \n```\n\n\n:::\n\n```{.r .cell-code}\nsf::sf_extSoftVersion()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H \n      \"3.12.1\"       \"3.13.3\"        \"9.9.0\"         \"true\"         \"true\" \n          PROJ \n       \"9.9.0\" \n```\n\n\n:::\n\n```{.r .cell-code}\nterra::gdal(lib = \"all\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    gdal  proj   geos   TBB\n1 3.13.3 9.9.0 3.12.1 FALSE\n```\n\n\n:::\n:::\n\n\n## The parcel\n\nThis is the polygon from the thread, as a plain coordinate matrix in\nLambert-93 (EPSG:2154, RGF93 on the GRS 1980 ellipsoid). It is about 40 m\nacross. We keep three versions of it: projected, transformed to longitude and\nlatitude (EPSG:4326), and with no CRS at all.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxy <- matrix(c(\n  320102.67, 6845954.56,\n  320111.85, 6845962.15,\n  320131.82, 6845971.55,\n  320134.33, 6845971.90,\n  320138.50, 6845953.21,\n  320141.93, 6845936.12,\n  320135.33, 6845935.07,\n  320118.58, 6845931.54,\n  320113.45, 6845929.91,\n  320105.18, 6845950.57,\n  320102.67, 6845954.56\n), ncol = 2, byrow = TRUE)\n\np   <- sf::st_sfc(sf::st_polygon(list(xy)), crs = \"EPSG:2154\")  ## projected\npll <- sf::st_transform(p, \"EPSG:4326\")                          ## longlat\np0  <- sf::st_set_crs(p, NA)                                     ## no crs\nll  <- sf::st_coordinates(pll)[, 1:2]\nseg_i <- seq_len(nrow(xy) - 1)\n```\n:::\n\n\nA small helper sets `sf_use_s2()` for one expression and restores it\nafterwards.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwith_s2 <- function(use, code) {\n  old <- suppressMessages(sf::sf_use_s2(use))\n  on.exit(suppressMessages(sf::sf_use_s2(old)))\n  force(code)\n}\n```\n:::\n\n\n## Three reference numbers\n\nBefore calling any sf or terra function, we compute the perimeter and area\ndirectly under each of the three models, so that every later result can be\nlabelled by which model it corresponds to.\n\n* **Planar**: each edge is a straight line in the projected coordinates, and\n  lengths and areas are Euclidean in those coordinates.\n* **Ellipsoid**: each edge is a geodesic on the WGS84 ellipsoid, computed with\n  Karney's algorithms (GeographicLib), here via geosphere.\n* **Sphere**: each edge is a great circle on a sphere of radius 6371010 m,\n  which is the radius s2 uses.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplanar_perim <- sum(sqrt(rowSums((xy[seg_i + 1, ] - xy[seg_i, ])^2)))\nplanar_area  <- abs(sum(xy[seg_i, 1] * xy[seg_i + 1, 2] -\n                        xy[seg_i + 1, 1] * xy[seg_i, 2])) / 2\n\nkarney_perim <- sum(geosphere::distGeo(ll[seg_i, ], ll[seg_i + 1, ]))\nkarney_area  <- geosphere::areaPolygon(ll)\n\nR_s2 <- 6371010\nsphere_perim <- s2::s2_perimeter(s2::as_s2_geography(pll), radius = R_s2)\nsphere_area  <- s2::s2_area(s2::as_s2_geography(pll), radius = R_s2)\n\nrefs_perim <- c(planar = planar_perim, ellipsoid = karney_perim, sphere = sphere_perim)\nrefs_area  <- c(planar = planar_area,  ellipsoid = karney_area,  sphere = sphere_area)\nrefs_perim\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    planar  ellipsoid     sphere \n129.248935 129.285384 129.098150 \n```\n\n\n:::\n\n```{.r .cell-code}\nrefs_area\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    planar  ellipsoid     sphere \n1049.65051 1050.24260 1047.02612 \n```\n\n\n:::\n\n```{.r .cell-code}\nwhich_number <- function(x, refs) {\n  hit <- names(refs)[abs(refs - x) / refs < 1e-6]\n  if (length(hit) == 0) \"OTHER\" else paste(hit, collapse = \"/\")\n}\n```\n:::\n\n\nThe perimeter is 129.249 m planar, 129.285 m on the ellipsoid and 129.098 m\non the sphere. The area is 1049.65, 1050.24 and 1047.03 square metres\nrespectively.\n\n### What each number is\n\nThe ellipsoidal length of an edge is the same as its planar length in an\nazimuthal equidistant projection centred on one of its endpoints, because that\nprojection preserves distance from its centre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naeqd_edge <- function(a, b) {\n  crs <- sprintf(\"+proj=aeqd +lon_0=%.12f +lat_0=%.12f +ellps=WGS84\", a[1], a[2])\n  q <- terra::project(rbind(a, b), from = \"EPSG:4326\", to = crs)\n  sqrt(sum((q[2, ] - q[1, ])^2))\n}\nc(aeqd = sum(vapply(seg_i, function(i) aeqd_edge(ll[i, ], ll[i + 1, ]), 0)),\n  karney = karney_perim)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      aeqd     karney \n129.285384 129.285384 \n```\n\n\n:::\n:::\n\n\nThe spherical number is the same geodesic calculation with zero flattening and\ns2's radius.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(geosphere::distGeo(ll[seg_i, ], ll[seg_i + 1, ], a = R_s2, f = 0))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 129.09815\n```\n\n\n:::\n:::\n\n\nThe planar number is the ellipsoidal number scaled by the projection. Lambert-93\nis conformal, so at a point it has a single scale factor k in every direction.\nLengths scale by k and areas by k squared. Measuring k numerically at the parcel\nreproduces both ratios.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk_perim <- planar_perim / karney_perim\nk_area  <- planar_area / karney_area\n\ncen <- colMeans(ll[seg_i, ])\nnb  <- geosphere::destPoint(cen, b = 45, d = 10)\ncq  <- terra::project(rbind(cen, nb), from = \"EPSG:4326\", to = \"EPSG:2154\")\nk_point <- sqrt(sum((cq[2, ] - cq[1, ])^2)) / 10\n\nc(k_point = k_point, k_perim = k_perim, k_perim_sq = k_perim^2, k_area = k_area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    k_point     k_perim  k_perim_sq      k_area \n0.999718096 0.999718077 0.999436234 0.999436238 \n```\n\n\n:::\n:::\n\n\nAt this location k is 0.999718, so the planar perimeter is 0.028% shorter than\nthe ellipsoidal one and the planar area is 0.056% smaller. An equal-area\nprojection centred on the parcel gives the ellipsoidal area to within about\none part in 10^8.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlaea <- sprintf(\"+proj=laea +lon_0=%.12f +lat_0=%.12f +ellps=WGS84\", cen[1], cen[2])\nc(laea = as.numeric(sf::st_area(sf::st_set_crs(sf::st_transform(pll, laea), laea))),\n  karney = karney_area)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      laea     karney \n1050.24259 1050.24260 \n```\n\n\n:::\n:::\n\n\n## How each package decides\n\n### sf\n\nThe decision in sf is visible in the source of `st_perimeter()`. The first\nbranch is taken when `sf_use_s2()` is `TRUE` and the geometry is longitude and\nlatitude.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbody(sf::st_perimeter)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n{\n    x = st_geometry(x)\n    if (sf_use_s2() && isTRUE(st_is_longlat(x))) {\n        if (!requireNamespace(\"s2\", quietly = TRUE)) \n            stop(\"package s2 required to calculate the perimeter of spherical geometries\")\n        units::set_units(s2::s2_perimeter(x, ...), \"m\", mode = \"standard\")\n    }\n    else {\n        if (isTRUE(st_is_longlat(x))) \n            units::set_units(st_length(st_boundary(x)), \"m\", \n                mode = \"standard\")\n        else {\n            if (!requireNamespace(\"lwgeom\", quietly = TRUE)) \n                stop(\"package lwgeom required, please install it first\")\n            lwgeom::st_perimeter_lwgeom(x)\n        }\n    }\n}\n```\n\n\n:::\n:::\n\n\nThe sf documentation for `st_area()` describes the same rule: with longitude\nand latitude coordinates, area is computed on the ellipsoid with\n`st_geod_area()` if `sf_use_s2()` is `FALSE`, and on the sphere with\n`s2_area()` if it is `TRUE`; with projected coordinates, area is computed in\nthe plane. `st_length()` and `st_distance()` follow the same pattern.\n\nWhen s2 is off, the longitude and latitude branch of `st_perimeter()` goes via\n`st_length(st_boundary(x))`. It does not call lwgeom's perimeter, which\ndeclines longitude and latitude input:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntryCatch(lwgeom::st_perimeter(pll), error = function(e) conditionMessage(e))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in lwgeom::st_perimeter(pll): 'lwgeom::st_perimeter' is deprecated.\nUse 'sf::st_perimeter or lwgeom::st_perimeter_lwgeom' instead.\nSee help(\"Deprecated\")\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"for perimeter of longlat geometry, cast to LINESTRING and use st_length\"\n```\n\n\n:::\n:::\n\n\n### terra\n\nterra has no global option for this. For longitude and latitude input, its\ndocumentation states that distances, lengths and areas are computed on the\nWGS84 ellipsoid with Karney's algorithms. For projected input, the behaviour\ndiffers between functions. `expanse()` and `cellSize()` have an argument\n`transform`, which defaults to `TRUE` and computes the result on the\nellipsoid. `perim()` and `distance()` have no such argument and work in the\nplane.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvp  <- terra::vect(p)\npts <- terra::vect(xy[1:2, ], crs = \"EPSG:2154\")\nr   <- terra::rast(terra::ext(320100, 320150, 6845925, 6845975), res = 10, crs = \"EPSG:2154\")\nunlist(list(\n  perim          = terra::perim(vp),\n  expanse        = terra::expanse(vp),\n  expanse_plane  = terra::expanse(vp, transform = FALSE),\n  distance       = as.numeric(terra::distance(pts)),\n  cellSize       = terra::global(terra::cellSize(r, unit = \"m\"), \"mean\")[1, 1],\n  cellSize_plane = terra::global(terra::cellSize(r, unit = \"m\", transform = FALSE), \"mean\")[1, 1]\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         perim        expanse  expanse_plane       distance       cellSize \n   129.2489354   1050.2425993   1049.6505127     11.9113601    100.0564081 \ncellSize_plane \n   100.0000000 \n```\n\n\n:::\n\n```{.r .cell-code}\n## references for the distance row\nc(planar = sqrt(sum((xy[2, ] - xy[1, ])^2)), karney = geosphere::distGeo(ll[1, ], ll[2, ]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    planar     karney \n11.9113601 11.9147186 \n```\n\n\n:::\n:::\n\n\nThe area of a nominal 10 m by 10 m cell is 100.056 square metres on the\nellipsoid, which is 100 divided by k squared. The distance between the first\ntwo vertices is the planar value, 11.911 m, rather than the ellipsoidal\n11.915 m.\n\n## The grid\n\nNow every combination: four ways of asking for a perimeter, three ways of\nasking for an area, three versions of the polygon, and `sf_use_s2()` on and\noff. Each result is labelled by the reference number it matches.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninputs <- list(projected = p, longlat = pll, none = p0)\n\nperim_calls <- list(\n  \"sf::st_perimeter\"        = function(x) sf::st_perimeter(x),\n  \"sf::st_length(boundary)\" = function(x) sf::st_length(sf::st_boundary(x)),\n  \"sf::st_length(cast MLS)\" = function(x) sf::st_length(sf::st_cast(x, \"MULTILINESTRING\")),\n  \"terra::perim\"            = function(x) terra::perim(terra::vect(x))\n)\narea_calls <- list(\n  \"sf::st_area\"                     = function(x) sf::st_area(x),\n  \"terra::expanse\"                  = function(x) terra::expanse(terra::vect(x)),\n  \"terra::expanse(transform=FALSE)\" = function(x) terra::expanse(terra::vect(x), transform = FALSE)\n)\n\nrun_grid <- function(calls, refs) {\n  out <- expand.grid(call = names(calls), input = names(inputs), s2 = c(TRUE, FALSE),\n                     stringsAsFactors = FALSE)\n  out$value <- NA_real_\n  out$msg <- \"\"\n  for (i in seq_len(nrow(out))) {\n    f <- calls[[out$call[i]]]\n    x <- inputs[[out$input[i]]]\n    r <- tryCatch(\n      withCallingHandlers(\n        with_s2(out$s2[i], as.numeric(f(x))),\n        warning = function(w) {\n          out$msg[i] <<- conditionMessage(w)\n          invokeRestart(\"muffleWarning\")\n        }),\n      error = function(e) {\n        out$msg[i] <<- paste(\"ERROR:\", conditionMessage(e))\n        NA_real_\n      })\n    out$value[i] <- r\n  }\n  out$matches <- vapply(out$value, function(v) if (is.na(v)) \"-\" else which_number(v, refs), \"\")\n  out\n}\n\nwide <- function(g) {\n  w <- reshape(g[, c(\"call\", \"input\", \"s2\", \"matches\")],\n               idvar = c(\"call\", \"s2\"), timevar = \"input\", direction = \"wide\")\n  names(w) <- sub(\"^matches\\\\.\", \"\", names(w))\n  rownames(w) <- NULL\n  w\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperim_grid <- run_grid(perim_calls, refs_perim)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLinking to GEOS 3.12.1, GDAL 3.13.3, PROJ 9.9.0; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nwide(perim_grid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     call    s2 projected   longlat   none\n1        sf::st_perimeter  TRUE    planar    sphere planar\n2 sf::st_length(boundary)  TRUE    planar    sphere planar\n3 sf::st_length(cast MLS)  TRUE    planar    sphere planar\n4            terra::perim  TRUE    planar ellipsoid planar\n5        sf::st_perimeter FALSE    planar ellipsoid planar\n6 sf::st_length(boundary) FALSE    planar ellipsoid planar\n7 sf::st_length(cast MLS) FALSE    planar ellipsoid planar\n8            terra::perim FALSE    planar ellipsoid planar\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\narea_grid <- run_grid(area_calls, refs_area)\nwide(area_grid)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                             call    s2 projected   longlat   none\n1                     sf::st_area  TRUE    planar    sphere planar\n2                  terra::expanse  TRUE ellipsoid ellipsoid planar\n3 terra::expanse(transform=FALSE)  TRUE    planar ellipsoid planar\n4                     sf::st_area FALSE    planar ellipsoid planar\n5                  terra::expanse FALSE ellipsoid ellipsoid planar\n6 terra::expanse(transform=FALSE) FALSE    planar ellipsoid planar\n```\n\n\n:::\n:::\n\n\nThe three sf routes to a perimeter now agree with each other in every case,\nwhich was not true at the time of the original thread. With projected input,\nor no CRS, everything in sf is planar. With longitude and latitude input, sf\ngives the spherical number when s2 is on and the ellipsoidal number when it is\noff.\n\nterra does not read `sf_use_s2()`, so its rows are the same in both halves of\neach table. With longitude and latitude input it gives the ellipsoidal number\nfor both perimeter and area. With projected input, `perim()` is planar and\n`expanse()` is ellipsoidal. With no CRS, terra computes in the plane and warns\nthat the results may be wrong.\n\nFor longitude and latitude data, which is the common case for data arriving\nfrom files and web services, the two packages with their default settings\ngive different answers: sf gives 129.098 m and 1047.03 square metres, terra\ngives 129.285 m and 1050.24 square metres.\n\n## One option, two roles\n\nIn sf, `sf_use_s2()` selects the model for measures and also the engine for\npredicates and overlays. With s2 off, longitude and latitude geometries go to\nGEOS, which treats the coordinates as planar. Measures, however, go to\nGeographicLib on the ellipsoid, where each edge is a geodesic. So within one\nsession with s2 off, the same polygon has ellipsoidal geodesic edges for the\npurpose of its area and straight edges in longitude and latitude for the\npurpose of point-in-polygon.\n\nThis matters for wide polygons at high latitude. A geodesic between two points\nat the same latitude does not follow the parallel; it bends toward the pole.\nHere is a box 120 degrees wide between 70 and 60 degrees south, and a point\njust inside its northern edge.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbx <- sf::st_sfc(sf::st_polygon(list(rbind(\n  c(-60, -70), c(60, -70), c(60, -60), c(-60, -60), c(-60, -70)))),\n  crs = \"EPSG:4326\")\npt <- sf::st_sfc(sf::st_point(c(0, -62)), crs = \"EPSG:4326\")\n\nwith_s2(TRUE,  list(area = sf::st_area(bx),\n                    intersects = sf::st_intersects(bx, pt, sparse = FALSE)[1, 1]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$area\n3008488091024 [m^2]\n\n$intersects\n[1] FALSE\n```\n\n\n:::\n\n```{.r .cell-code}\nwith_s2(FALSE, list(area = sf::st_area(bx),\n                    intersects = sf::st_intersects(bx, pt, sparse = FALSE)[1, 1]))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nalthough coordinates are longitude/latitude, st_intersects assumes that they\nare planar\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$area\n3.027757e+12 [m^2]\n\n$intersects\n[1] TRUE\n```\n\n\n:::\n:::\n\n\nWith s2 on, the area is spherical and the point is outside the polygon, which\nis consistent: on the sphere the northern edge passes south of 62 degrees\nsouth at longitude 0. With s2 off, the area is ellipsoidal, which is the more\naccurate model, but the point is now inside the polygon, because GEOS treats\nthe northern edge as the straight line at 60 degrees south. A user who\nswitches s2 off to obtain ellipsoidal measures therefore also changes the\nanswers to spatial predicates, and the measures and predicates no longer\ndescribe the same polygon.\n\n## Point distance and two spheres\n\nFor a single pair of points (the first two vertices of the parcel) there is a\nfourth number.\n\n\n::: {.cell}\n\n```{.r .cell-code}\na <- ll[1, , drop = FALSE]\nb <- ll[2, , drop = FALSE]\npa <- sf::st_sfc(sf::st_point(a), crs = \"EPSG:4326\")\npb <- sf::st_sfc(sf::st_point(b), crs = \"EPSG:4326\")\nc(\n  sf_s2     = with_s2(TRUE,  as.numeric(sf::st_distance(pa, pb))),\n  sf_nos2   = with_s2(FALSE, as.numeric(sf::st_distance(pa, pb))),\n  terra_geo = terra::distance(a, b, lonlat = TRUE),\n  terra_hav = terra::distance(a, b, lonlat = TRUE, method = \"haversine\"),\n  geodist   = geodist::geodist(a, b, measure = \"geodesic\"),\n  karney    = geosphere::distGeo(a, b),\n  planar    = sqrt(sum((xy[2, ] - xy[1, ])^2))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     sf_s2    sf_nos2  terra_geo  terra_hav    geodist     karney     planar \n11.8954624 11.9147186 11.9147186 11.9087694 11.9147186 11.9147186 11.9113601 \n```\n\n\n:::\n:::\n\n\nsf with s2 off, terra's default method, geodist and geosphere all agree on the\nellipsoidal distance. sf with s2 on gives the spherical distance. terra's\n`method = \"haversine\"` gives a third value, because it uses a sphere with the\nequatorial radius of WGS84 rather than s2's mean radius:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(terra_hav      = terra::distance(a, b, lonlat = TRUE, method = \"haversine\"),\n  hav_equatorial = geosphere::distHaversine(a, b, r = 6378137),\n  hav_mean_s2    = geosphere::distHaversine(a, b, r = R_s2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     terra_hav hav_equatorial    hav_mean_s2 \n    11.9087694     11.9087694     11.8954624 \n```\n\n\n:::\n:::\n\n\nThe two spheres differ in radius by a factor of 1.0011, so \"spherical\ndistance\" is itself not one number.\n\n<!-- TODO check at terra tip: the SpatRaster distance() method appeared to\ndefault to method = \"haversine\" in the CRAN source I read. Confirm with\n  getMethod(\"distance\", signature(x = \"SpatRaster\", y = \"missing\"))\nand mention here if it still does. -->\n\n## How large is the difference, and where?\n\nFor a 40 m parcel the differences are centimetres. It is tempting to conclude\nthat the choice of model only matters for large polygons. For the sphere\nagainst the ellipsoid, that is not the case: the relative error in area is set\nby latitude and is essentially the same for a box one metre across and a box\none degree across.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbox <- function(lon0, lat0, size) {\n  m <- rbind(c(lon0, lat0), c(lon0 + size, lat0), c(lon0 + size, lat0 + size),\n             c(lon0, lat0 + size), c(lon0, lat0))\n  sf::st_sfc(sf::st_polygon(list(m)), crs = \"EPSG:4326\")\n}\nsweep_lat <- function(size, lats = seq(-89.5, 89.5 - size, by = 1)) {\n  do.call(rbind, lapply(lats, function(lat0) {\n    g <- box(147, lat0, size)\n    k <- geosphere::areaPolygon(sf::st_coordinates(g)[, 1:2])\n    data.frame(lat = lat0 + size / 2, size = size,\n               s2 = with_s2(TRUE, as.numeric(sf::st_area(g))) / k - 1,\n               terra = terra::expanse(terra::vect(g)) / k - 1)\n  }))\n}\nsw <- rbind(sweep_lat(0.001), sweep_lat(0.1), sweep_lat(1))\nrange(sw$terra)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0 0\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(sw$lat, 100 * sw$s2, type = \"n\", xlab = \"latitude\",\n     ylab = \"area error vs ellipsoid (%)\", main = \"s2 sphere vs Karney ellipsoid\")\nsizes <- unique(sw$size)\nfor (s in sizes) {\n  d <- sw[sw$size == s, ]\n  lines(d$lat, 100 * d$s2, lty = match(s, sizes))\n}\nabline(h = 0, col = \"grey\")\nlegend(\"topright\", legend = paste(sizes, \"deg box\"), lty = seq_along(sizes))\n```\n\n::: {.cell-output-display}\n![Relative error of s2 spherical area against Karney ellipsoidal area, by latitude, for square boxes of three sizes. The three curves coincide.](index_files/figure-html/sweep-plot-1.png){width=672}\n:::\n:::\n\n\nThe spherical area is 0.45% too large at the equator, correct near 35 degrees\nnorth and south, and 0.89% too small near the poles. At the latitudes of the\nSouthern Ocean and Antarctica the spherical area is consistently between 0.5%\nand 0.9% smaller than the ellipsoidal area, regardless of the size of the\npolygon. terra agrees with Karney to within floating point precision\nthroughout, since it uses the same library.\n\nPlanar error behaves differently: it depends on the projection's scale factor\nover the polygon, which for a well-chosen local projection is small for small\npolygons and grows with distance from the projection's centre or standard\nlines.\n\n## What is an edge?\n\nAll of the above assumes that everyone agrees on what the polygon is. The\ncoordinates alone do not determine that. Between two vertices, an edge could\nbe a geodesic on the ellipsoid, a great circle on the sphere, a straight line\nin some projection, or a line of constant latitude. For small polygons these\ncoincide closely. For large ones they do not.\n\nHere is a box 10 degrees on each side at 60 degrees south, first with only its\nfour corners, then densified at 0.1 degree spacing along its edges in\nlongitude and latitude so that the northern and southern edges follow the\nparallels.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb1  <- box(147, -60, 10)\nb1d <- sf::st_set_crs(sf::st_segmentize(sf::st_set_crs(b1, NA), 0.1), \"EPSG:4326\")\nc(\n  corners_karney   = geosphere::areaPolygon(sf::st_coordinates(b1)[, 1:2]),\n  densified_karney = geosphere::areaPolygon(sf::st_coordinates(b1d)[, 1:2]),\n  corners_terra    = terra::expanse(terra::vect(b1)),\n  densified_terra  = terra::expanse(terra::vect(b1d))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  corners_karney densified_karney    corners_terra  densified_terra \n    709651946744     711460602143     709651946744     711460602143 \n```\n\n\n:::\n:::\n\n\nThe two versions differ in area by 0.25%, which is of the same order as the\ndifference between the sphere and the ellipsoid at this latitude. terra and\nKarney agree on each version, so both treat the edges as geodesics and neither\ndensifies implicitly.\n\nThe same question applies to terra's `transform = TRUE` for projected\npolygons. The vertices are transformed to longitude and latitude and the edges\nare then treated as geodesics. An edge that is straight in the projection is\nnot a geodesic, so for large polygons the result is the ellipsoidal area of a\nslightly different polygon. Densifying in the projected coordinates before\nmeasuring removes this.\n\n## Summary\n\n| input | sf, s2 on (default) | sf, s2 off | terra |\n|---|---|---|---|\n| longitude/latitude, length and perimeter | sphere | ellipsoid | ellipsoid |\n| longitude/latitude, area | sphere | ellipsoid | ellipsoid |\n| projected, length and perimeter | planar | planar | planar |\n| projected, area | planar | planar | ellipsoid (`transform = FALSE` for planar) |\n| no CRS | planar | planar | planar, with a warning |\n\nFor longitude and latitude data, terra's rule can be stated in one line: it\nalways measures on the ellipsoid. sf's answer depends on an option that is set\nper session, is on by default, and also determines how predicates and\noverlays are computed. The consequence is that an sf user who wants\nellipsoidal measures has to change the behaviour of their spatial predicates\nas well, and a user who leaves the default gets a spherical measure whose\nerror varies from +0.45% to -0.89% with latitude, independent of the size of\nthe feature.\n\nTwo changes would make each package's rule simpler to state. In sf, a way to\nselect the ellipsoid for measures independently of the engine used for\npredicates, for example an argument to the measure functions or a separate\noption. In terra, extending the `transform` argument to `perim()` and\n`distance()`, so that projected input is measured on the ellipsoid for every\nquantity whenever the CRS is known, as it already is for area.\n\nIn the meantime, the grid above can be run against any installed versions,\nand is a quick way to check which number a given function returns.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}